### ISSUE TITLE
Windows debug libs are gargantuan

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#1062]
**Describe the bug**
The Babylon Native Windows static libs (debug) are quite large, and in fact too large now to be packaged into an npm package for Babylon React Native and published to npmjs.org (e.g. https://github.com/BabylonJS/BabylonReactNative/runs/6043625321?check_suite_focus=true).

Some of the most notable large libs are (note each of these are built for four architectures, so multiple the package size impact by four!):
- Graphics.lib: ~48mb
- Canvas.lib: ~20mb
- MachineIndependent.lib: @25mb
- NativeEngine.lib: ~20mb
- NativeXR.lib: ~20mb
- openxr_loaderd.lib: ~20mb
- spirv-*.lib: ~15mb - ~20mb each

@bghgary did a little initial digging on Graphics.lib and found a couple of things:
1. "just including <winrt/Windows.UI.Xaml.Controls.h> without using any types causes the size to go kaboom" (e.g. ~6mb -> 44mb for his local build)
2. Somewhere between the BRN 1.0.1 release and 1.1.0 release, Graphics.lib increased from ~27mb to ~48mb (unknown reason currently)

**Expected behavior**
Libs should be small enough to publish BRN to npmjs.org.

**Other**
 - Platform: UWP

**Comment by tymlipari** [comment]
C++/WinRT makes extremely heavy use of template specialization which tends to blow up static libraries. We should consider experimenting with the `WINRT_LEAN_AND_MEAN` macro to see if that improves things.

Another thing we'd wanted to look at in the past was whether or not we could consume the core BabylonNative libraries as a dynamic library rather than statically linking it so that the only static libs we need to ship in the BRN package is just the code that hooks up the native XAML component to RN. It'll still be bloated (because C++/WinRT) but the core BabylonNative DLL will probably only be a couple of megs.

**Comment by bghgary** [comment]
Other options we are considering:
- Compile the debug libraries basically as release except against the debug C++ runtime
- Split the Windows npm packages into different flavors

**Comment by bghgary** [comment]
Just tested, `WINRT_LEAN_AND_MEAN` macro has no effect on static lib size for debug.

**Comment by CedricGuillemet** [comment]
Did a 1st PR on BN : https://github.com/BabylonJS/BabylonNative/pull/1085
Work/test on BRN in progress.

**Comment by bghgary** [comment]
PR: https://github.com/BabylonJS/BabylonReactNative/pull/416
