### ISSUE TITLE
crash with 1-float attribute vertex stream

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#1175]
forum thread : https://forum.babylonjs.com/t/bgfx-babylon-native-bug-when-using-float-vertex-buffer-shader-attribute/36158

Vertex stream with 1 float stream crashes BN (in shader creation as it looks) whereas using a vec2 instead works fine.

**Comment by sebavan** [comment]
This does not crash on Windows FYI, but we reproed on another project on Android. (did not had a chance to test on IOS) but just to let you know it might be platform specific.

**Comment by bghgary** [comment]
At least investigate what the problem is.

**Comment by SergioRZMasson** [comment]
The problem seems to be related to a bug when glslang parsers an "AssignmentMultiplicationVectorByFloat" operation. The problem is not related to the usage of a float buffer itself, but to the instruction where the UV vec2 gets multiplied by a float.

Replacing the shader code with the code below make the code work and also uses a float vertex buffer:

```
BABYLON.Effect.ShadersStore["customVertexShader"]= "\r\n"+   
		"precision highp float;\r\n"+

    	"// Attributes\r\n"+
    	"attribute vec3 position;\r\n"+
    	"attribute vec2 uv;\r\n"+
        "attribute float side;\r\n"+

    	"// Uniforms\r\n"+
    	"uniform mat4 worldViewProjection;\r\n"+

    	"// Varying\r\n"+
    	"varying vec2 vUV;\r\n"+

    	"void main(void) {\r\n"+
    	"    gl_Position = worldViewProjection * vec4(position, 1.0);\r\n"+

    	"    vec2 sidev = vec2(side, side);\r\n"+
        "    vUV = uv * sidev;\r\n"+
    	"}\r\n";
```

This bug seems to be related to glslang, maybe updating to a more recent version might fix it.

**Comment by SergioRZMasson** [comment]
After updating glslang and SPIRV-Cross this issue was fixed. PR #1285
