### ISSUE TITLE
Using Typescript in BabylonNative reports error

### ISSUE THREAD

**Issue by giraphics** [BabylonJS/BabylonNative#1200]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Describe the bug**
I am creating a BabylonJS simple hello world simple program using Typescript and getting errors. 

**To Reproduce**
1. Go to https://github.com/giraphics/BabylonNativeGLFW/tree/typescriptBabylonJS
2. Following ReadMe.md for build instruction
3. The typescript program is written in [game.ts](https://github.com/giraphics/BabylonNativeGLFW/blob/typescriptBabylonJS/Scripts/game.ts)
4. Execution of the program in MacOS produces the following error:-

```
2023-01-23 18:21:18.109541+0800 BabylonNativeExample[89142:1530660] Uncaught Error: Unexpected token ':'. Expected a ')' or a ',' after a parameter declaration.
Program ended with exit code: 0
```

It is difficult to learn where the error is appearing in the code. However, the error provides hints to point out this [function signature](https://github.com/giraphics/BabylonNativeGLFW/blob/typescriptBabylonJS/Scripts/game.ts#L8).

**Question 1:** Is there any other way to point out the error in the JS or TS code?

**Question 2:** How to properly use typescript in BabylonJSNative. Note that the program work fine if we change the function signature to JS style:-

```
function  CreateScene(engine)  
{
 . . . more code goes herer
}

```

**Other**
 - Platform: [MacOS]

**Comment by SergioRZMasson** [comment]
Hello @giraphics , how are you doing? 

The Javascript runtimes that are used in Babylon Native (V8, Chakra, JavaScriptCore) do not support using Typescript. This is pretty standard since browsers also do not run Typescript directly.

In order for Typescript to run at any Javascript runtime it need to be transpired into Javascript.

If you wish to use Typescript into you project, you will probably have to setup a custom build pipeline that takes your typescript code and generates javascript files, and than use those files in your Babylon Native application.
