### ISSUE TITLE
Resize window causes failed assertion

### ISSUE THREAD

**Issue by bnolan** [BabylonJS/BabylonNative#151]
Got it to run on MacOS, works great! When I resize the window I get this abort:

```
validateFunctionArguments:3531: failed assertion `Fragment Function(xlatMtlMain): missing sampler binding at index 0 for _mtlsmp_s_texColor[0].'
```

![Screen Shot 2020-02-13 at 10 38 27 AM](https://user-images.githubusercontent.com/17499/74379658-1893a900-4e4d-11ea-8feb-e32ef8bfca0b.png)

**Comment by syntheticmagus** [comment]
**WORKAROUND**: Replace the [`bgfx::touch(0);` call in `UpdateSize`](https://github.com/BabylonJS/BabylonNative/blob/3c9e3938fe3604e9b88f1673788426782413ddd7/Library/Source/NativeEngine.cpp#L410) with `bgfx::frame();`

Very curious, not sure if this is a BGFX bug or a problem in the way we're using it. Issue repros as soon as I try to resize the window, but the assert in question stops firing if I just comment out the `bgfx::touch` call inside `UpdateSize`. However, if I just do that, a different assert starts to fire only when resizing the window to be smaller, which states that the scissor rect must be no larger than the render pass. I wonder if there's a bit of a chicken-egg problem with this where certain aspects of the reset aren't actually applied until `bgfx::frame` is called, causing internal state to get misaligned for Metal if `bgfx::frame` isn't called immediately after the resize. I'm quite certain calling `bgfx::frame` instead of `bgfx::touch` in `UpdateSize` isn't the *right* thing to do, but hopefully it might be an adequate workaround to unblock you while we dig in and find out more about what's actually going on.

@CedricGuillemet, does this issue/workaround repro for you?

**Comment by CedricGuillemet** [comment]
I know this issue, it's on my todo list. Basically, UIKit events happen in main thread. rendering is done in another. When the CALayer is resized, bgfx state is still using the previous one. This gives metal validation issue. When resizing, the idea is to flush the rendering, resize the CALayer, then resume rendering. I already have a mutex for that....fixing it today!

**Comment by CedricGuillemet** [comment]
My test with suspend/resume during resize didn't work. Calling bgfx::frame looks like a good workaround. I agree with you, some state are updated when calling that function.
It tested it with win32 and mac. With uwp, the resize is different. I get an update half a second after the resize.

**Comment by CedricGuillemet** [comment]
Tested OK on Android. I did the change in this PR : https://github.com/BabylonJS/BabylonNative/pull/153
There is already an issue filled for resizing with UWP.

**Comment by syntheticmagus** [comment]
Unfortunately the workaround seems to cause problems on Win32. On that platform, resize updates come so rapidly from the OS that calling `bgfx::frame`, which is currently blocking because we're in single-threaded mode, causes the resizes to "queue up" in the task chain and effectively block program execution until the resize queue is drained.

It seems the thing that Metal gets mad about is if you have other graphics calls happening on the same frame where you're resizing. That seems like a behavior I would have expected bgfx to hide from us, so we might want to start a discussion about that over there. Spoke offline with @bghgary, and for now we're going to address this using compiler flags to change the behavior for Apple platforms only, at least until we can delve into the problem more deeply.

**Comment by bghgary** [comment]
Closing since the assertion is fixed. See #118 for fixing further resize issues.
