### ISSUE TITLE
Playground demo: crash on MacOS in N-API

### ISSUE THREAD

**Issue by ptc-rgrasset** [BabylonJS/BabylonNative#165]
MacBoo Pro (15 inch 2017) 
MacOS Mojave 10.14.6 (18G87)
XCode Version 11.3 (11C29)

Cloned repo as per today, followed the build instructions from README.md.

Running Playground app from Xcode, tried debug and release, same outcome:
crash is triggered from ViewController.mm, l62:
`    loader.LoadScript("babylon.max.js");`

and crash in js_native_api_Javascript_core.cc, l218:
`  JSStringRef stringRef = JSValueToStringCopy(env->m_globalContext, reinterpret_cast<JSValueRef>(value), nullptr);
`
Thread 6: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

(I additionally tried to setup the XCode custom working directory to the script directory, it didn't help)

<img width="1468" alt="babylonnative_napi_crashlog" src="https://user-images.githubusercontent.com/15635690/75718750-cddeb180-5cd3-11ea-84c2-aaa0f9154fc0.png">

**Comment by syntheticmagus** [comment]
Hi ptc-rgrasset,

I think @CedricGuillemet's fixed this bug yesterday afternoon in #163. Can you pull latest master and try again? Thanks!

**Comment by CedricGuillemet** [comment]
Hi @ptc-rgrasset 

Did you test with latest changes on master? It should work as expected now.

**Comment by bghgary** [comment]
@ptc-rgrasset Let us know if you see other issues.

**Comment by ptc-rgrasset** [comment]
Really sorry for the delay (with everything happening right now I didn't get a chance to retest that before)

I have re-tested with master tip, and I now get another crash:
<img width="1595" alt="BN_Playground_MacOS_Debug" src="https://user-images.githubusercontent.com/15635690/78060177-64fa6000-738b-11ea-8f82-6bd479c272f7.png">

**Comment by imbrig** [comment]
@bghgary @ptc-rgrasset I'm experiencing the same throw when `loader.LoadScript("babylon.max.js");` is called.

MacBook Pro (15-inch, 2018)
MacOS Mojave 10.14.6
XCode Version 11.3
Python 3.7.7
cmake version 3.17.0
Followed the directions on the Readme.

Since I have bootcamp and Windows 10 VS2019, I tried it there and the Playground worked.
Someone I know has the same hardware but on Catalina(10.15.4) and XCode 11.4 and the Playground worked without issues.

![Screen Shot 2020-03-31 at 3 11 22 PM](https://user-images.githubusercontent.com/47464835/78080249-b3473900-7362-11ea-9ee8-ea7ec9b8104e.png)
