### ISSUE TITLE
`FlipY` could be done with fewer copies

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#187]
As originally written, `FlipY` does (3 _n_ / 2) copies when flipping an image, where _n_ is the height of the image in pixels. It does this because it operates under an exchange logic, traversing the image from the top and bottom simultaneously and swapping rows as it goes. Thus, for each pair of rows, it does one copy operation to move one row into a temporary buffer, one copy to replace that row's original memory with the other row, and one copy to replace the second row with the data from the buffer. This copy count could probably be reduced to (_n_ + 1) by just allocating a bigger buffer and copying an entire half of the image--WLOG, the top half--into it in a single operation. The bottom half could then be inverted into the top half row by row, and then the buffer could be inverted into the bottom half row by row.

**Comment by CedricGuillemet** [comment]
This looks like a candidate for some benchmark!
Code is here :  https://github.com/CedricGuillemet/dump/blob/master/testFlipY.cpp
I run 10000iterations on a 1024x1024x4 image and I measure the time it takes.
Please review my code. I didn't add a validation pass but I carefully checked my code...a mistake is always possible.
Any, the results:
```
time 3n/2 : 1.22649
time proposal 1 : 12.4568
time proposal 1b : 11.8881
time proposal 1c : 5.28774
time proposal byteswap : 22.6513
time proposal byteswap no temp: 0.989421
time proposal uint64_t swap : 1.54567
time proposal uint64_t swap no temp : 0.97753
```

'time 3n/2' is what we use now and it's the reference.
'time proposal 1' : your proposed algorithm (correct me if I'm wrong). 10x slower. I don't understand why.
'time proposal 1b': same algorithm with better arithmetics for pointer computation. small improvement
At that point, I was thinking, maybe the vector allocation might take some time, so using a static.
'time proposal 1c': static vector, 1 allocation. 50% faster but still...
'time proposal byteswap' Dumb idea: simple byteswap with temp variable. as expected, it's crap :D
'time proposal byteswap no temp': use arithmetics instead of a uint8_t on the stack. ~20% faster than the reference. I'm surprised!
'time proposal uint64_t swap': why not... faster but not as good as the reference
'time proposal uint64_t swap no temp' arithmetics wins again.

All tested in x64, release max optim.
I think the cache explains why the 10x performance drop. At my biggest surprise, the byteswap performs well. I believe the LHS would make it behave way worse.

**Comment by syntheticmagus** [comment]
Just saw this reply. Very cool, awesome benchmark! Very interesting findings. It seems super strange that the naive half-buffer proposal would be *so* slow; there must be something I don't quite understand here.

**Comment by CedricGuillemet** [comment]
Yes, same for me. I could imagine something 2times slower because of cache miss but 10times is a lot. I didn't profile it with VS performance test. But I guess the hot point would be on memcpy. I didn't expect the byteswap to be faster.

**Comment by CedricGuillemet** [comment]
@syntheticmagus Can we close this issue or do you want to do more tests?

**Comment by CedricGuillemet** [comment]
Talked to @syntheticmagus . Closing.
