### ISSUE TITLE
OpenGL shader compilation

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#211]
OpenGL shader compilation is a bit more complicated than Metal or D3D because of many GLSL versions (for ES, desktop,...) and bgfx adding preprocessors, version and output indirection.
Here are issues to fix:

# Uniforms structure

Shaders coming from bjs have uniforms in a structure called 'Frame'. bgfx doesn't suport uniforms inside a struct. only global uniform can be retrieved and used. bgfx doesn't allow block uniforms. With Metal, it's a bit different. You have to use a structure (part of metal language) but bgfx needs that structure to have a particular name (see https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerMetal.cpp#L41 for reference)
What is done for now, is to use reflection in GLSLang, get uniforms names from that structure and add strings on top of shader that way:
```
uniform highp vec4 nameOfShaderInStructure;
```
This is done here:
https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L58
A check is done on the uniform type (vec4 or mat4) here : https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L62
bgfx only supports vec4 or mat4. The conversion is done is nativeShaderProcessor.ts  https://github.com/BabylonJS/Babylon.js/blob/c0a1265b2b69be84378ac8ccc52e70ef1510f469/src/Engines/Native/nativeShaderProcessor.ts#L93
So, to sum up, shader uniforms must be global (not in a structure) for OpenGL, not for D3D or Metal. This can be done in nativeShaderProcessor (depending on rendering api, create a structure or not)

# bgfx version
depending on shader language version, bgfx checks and add some preprocessor defines. Like '#version'
https://github.com/bkaradzic/bgfx/blob/ea4bbbfcb7f4febc93739acbacf9104cd85bd214/src/renderer_gl.cpp#L6163
as there can only 1 version at the top of the file, any #version already in the shader will give an error. A hack is done for ES3.0 here https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L130
I believe this can be fixed in nativeShaderProcessor.ts by removing the version Desktop. 
On Linux the version for more of a problem with more strict policy on GLSL language features available or not. On Windows, it was less an issue.

# bgfx fragment output
As the #version, bgfx might change the fragment output to fit its need: https://github.com/bkaradzic/bgfx/blob/ea4bbbfcb7f4febc93739acbacf9104cd85bd214/src/renderer_gl.cpp#L6268
This was counterbalanced with a string replacement https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L133
Check if it can also be fixed in the shader processor.
Also note, depending on the glsl shader language version, the output is different. gl_fragColor is deprecated GLSL 1.3 (OpenGL 3.0) but might still be used. So there is some confusion in the output that needs to be addressed.

# Textures and samplers
Depending on the output glsl version, the textures and samplers are declared differently. GLSLang does a part of the job but the names of the samplers and textures and incorrect: It's using a texture name instead of a sampler name. bgfx keeps tracks of the texture names and bjs bind sampler names. This mismatch is fixed by renaming things here:
https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L108
The reassociation if done by combined_id here
https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L112
This is not very robust. Moreover, in order to get the combined_id, build_combined_image_samplers() is called and (might) be a big performance drop.
https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L41

# Closing thoughts

I think most work should be done in nativePreprocessor depending on the GLSL output version and api backend of course. It's possible to work on Windows if the shaderCompiler is set to Opengl (change cmake file) and api backend set to opengl here : https://github.com/BabylonJS/BabylonNative/blob/1b40d7b59b6e4d01dd4b9bb1db4f0349a5d03cc6/Plugins/NativeEngine/Source/NativeEngine.cpp#L317
The difficult part is to make is work on 2 or 3 platforms (Linux, Android and potentially, Windows) without breaking ouput for Metal and Direct3D.
Getting the default experience.js working with the cube is a first step. marbletower.js is also a good test. Particularly for samplers/texture as there are 4 bound textures for the tower and none for the marbles.

**Comment by CedricGuillemet** [comment]
Related issue : https://github.com/BabylonJS/BabylonNative/issues/254

**Comment by acoget** [comment]
Re: uniforms structure. Turns out that glslang gets very sad when passed non-opaque (i.e. value type) uniforms outside a struct, because ShaderCompilerOpenGL currently pretends it's targeting Vulkan.
https://github.com/BabylonJS/BabylonNative/blob/5f4eade667933897a4139c3e7f7c1b0920250840/Plugins/NativeEngine/Source/ShaderCompilerOpenGL.cpp#L20
Obviously that can be fixed, but it triggers parsing errors on the textures. The Javascript separates the textures and samplers for all target APIs:
https://github.com/BabylonJS/Babylon.js/blob/16de32c7a388d2ccd4a5b834c7193d5b50814144/src/Engines/Native/nativeShaderProcessor.ts#L99
But in doing so, it outputs a "texture[type]" object, which was never a valid type in GLSL. I am honestly surprised that this works for other target APIs.

The result is that uniform structs and textures will have to be fixed together so things keep working, so this might turn into one big PR on each repo rather than separate small ones.

**Comment by acoget** [comment]
Turns out we're outputting and processing Vulkan GLSL, which is why the texture syntax looks nothing like regular GLSL. setEnvClient is not the target language, but the one being parsed. My bad.
This gets very tangled, because what we want is:
- names that match between the SPIRVCross reflection info passed in the bgfx header, and the GL reflection info bgfx gets from the shader source;
- said names probably also need to match some internal data caching used to set uniforms and textures, but I haven't even made it that far without things breaking;
- minimal name rewriting (i.e. minimal direction string manipulation), since e.g. rewriting a uniform name that also serves as a function parameter name elsewhere will break the shader;
- minimal logic on the C++ side.

This means that "just" outputting the uniforms as globals rather than a struct turns into the following white rabbit hunt:
- Change the JS to output global uniforms;
- glslang breaks, because that's invalid in Vulkan GLSL;
- Change glslang parameters to use GL GLSL;
- textures break, because they're output Vulkan-style;
- Change textures to only output the samplers and skip the sampling rewriting;
- everything breaks, because neither the uniforms nor the textures (declared as samplers) show up in SPIRVCross reflection;
- Switch back to Vulkan GLSL and try a different approach.

On the bright side, this will make for very minimal divergences in Javascript since it'll output Vulkan GLSL no matter what, and ShaderCompilerOpenGL will just do what it can to fix up the reflection data so it lines up without string replacement hacks.

**Comment by acoget** [comment]
The current best solution is:
- No changes at all to JS: output separate samplers and textures, and a uniform buffer struct.
- ShaderCompilerOpenGL creates combined samplers but renames them and re-adds the bindings before outputting translated GLSL. It also sets the "emit plain uniforms" option so the resulting uniforms will have valid locations in GL reflection.
- NativeEngine keeps track of the mapping between qualified in-struct names and plain names, so it can output qualified names that will match GL reflection AND remap them back to the name Babylon expects.

Unfortunately that still doesn't quite work. Since the uniforms get output to two different structs, they get different qualified names: the same uniform in the vertex and fragment stages therefore becomes two uniforms, but only gets set once. If I can't work around that, the only option will be rewriting uniforms in the shader string after SPIRV-Cross outputs it, just like it's currently done.

**Comment by acoget** [comment]
Trying to work around it yield a link error as seen before. If the names match between stages in the shader source, which is necessary for bgfx to combine them, then the GLSL linker complains that the structs have different types / usage.
The only options are:
- modifying the source code after emitting, as we were already doing.
- convincing SPIRV-Cross to add a new block emission mode.

Currently, SPIRV-Cross will always emit a struct, no matter how much you fiddle with the options. See https://github.com/KhronosGroup/SPIRV-Cross/blob/61cddd6307ef8a644462bc1263d196e1bae9ec67/spirv_glsl.cpp#L1870 if using a UBO, and https://github.com/KhronosGroup/SPIRV-Cross/blob/61cddd6307ef8a644462bc1263d196e1bae9ec67/spirv_glsl.cpp#L1823 if using push constants.

**Comment by acoget** [comment]
Commits on my fork for documentation:
- Non-working, with fully qualified uniform names and attempted de-deduplication plus extraneous samplers wrangling in NativeEngine: https://github.com/acoget/BabylonNative/commit/d6ba22e70d22cc9edc7e5fc65d1720a471f6813a
- Working, without the extraneous samplers wrangling, and with string manipulation to output uniforms in the right format: https://github.com/acoget/BabylonNative/commit/7b91fc555ae69ce721958c48cbf7fe33a7eb8cff

**Comment by acoget** [comment]
Version string: SPIRV-Cross always emits it, so the hack has to stay in the last step.
https://github.com/KhronosGroup/SPIRV-Cross/blob/61cddd6307ef8a644462bc1263d196e1bae9ec67/spirv_glsl.cpp#L646

**Comment by acoget** [comment]
fragColor: SPIRV-Cross always prefixes gl_ names with an extra underscore to avoid conflicts with built-ins. Same thing, the hack has to stay in the last step.
https://github.com/KhronosGroup/SPIRV-Cross/blob/61cddd6307ef8a644462bc1263d196e1bae9ec67/spirv_glsl.cpp#L2388

**Comment by acoget** [comment]
In conclusion, taking the problems in the order they were presented in the issue.
**Uniforms structure**
Can't be fixed in JS: global value type uniforms are invalid in Vulkan GLSL (which we use) and don't show up in SPIRV-Cross reflection (which we use to build the bgfx header) with GL GLSL.
Can't be fixed by using a struct and remapping names in reflection. If the struct names match between vertex and fragment shaders, GLSL gets a link error due to different types. If the struct names don't match, the uniforms get duplicated and only set once.
Actual fix: emit the uniforms as globals via the SPIRV-Cross compiler header as before. The only change in the linked commits is using SPIRV-Cross reflection rather than glslang, which comes out slightly cleaner.
**bgfx version**
Can't be fixed. SPIRV-Cross always emits a version string, and bgfx always adds its own unless it's #version 430. The hack needs to stay string-based and after SPIRV-Cross emission.
**bgfx fragment output**
Can't be fixed. SPIRV-Cross always renames variables that start with gl_. The hack needs to stay string-based and after SPIRV-Cross emission.
**Textures and samplers**
This is the only one that could be significantly improved. The combined samplers that are built and used by SPIRV-Cross to emit GLSL can be renamed and rebound before code emission, resulting in the correct output without string manipulation.

As discussed with @CedricGuillemet, all of this is going to be rewritten anyway, to limit how much string manipulation is done by nativeProcessor.ts, and to try to rely on glslang reflection rather than SPIRV-Cross for GLSL output.
This will require duplicating most of the reflection / bgfx header-building logic in NativeEngine, and success will greatly depend on what APIs glslang actually exposes. My gut feeling after a month deep in this system is that glslang will not provide sufficient info and that SPIRV-Cross will have to stay, but it's worth a try!

**Comment by CedricGuillemet** [comment]
Fixed! Thanks to @syntheticmagus PR
