### ISSUE TITLE
add a way to protect the javascript.

### ISSUE THREAD

**Issue by IuryBorges1993** [BabylonJS/BabylonNative#301]
add a way to protect the javascript code in babylon native.

**Comment by bghgary** [comment]
Can you explain what you mean by "protect the javascript"?

**Comment by IuryBorges1993** [comment]
protect javascript code against possible snooping

**Comment by IuryBorges1993** [comment]
I even looked inside the apk and saw the javascript code so that someone else can copy it.

**Comment by IuryBorges1993** [comment]
In the godot engine you can encrypt your code

**Comment by bghgary** [comment]
The example apps have full JavaScript that have not been minified. Once minified, it is harder to decipher the code.

Barring that, this seems like something that can be added with a custom plugin. Feel free to contribute one. 😏

**Comment by bghgary** [comment]
Another possibility is to pre-parse the JavaScript which makes it harder, but it's not as good as typical obfuscation.

**Comment by IuryBorges1993** [comment]
I can do a type of encryption that only those who reverse engineer can discover.

I use RSA + substitution of numbers by strings, impossible for anyone to be able to decipher, I call myself RSA evolution

**Comment by IuryBorges1993** [comment]
What do you think?

**Comment by IuryBorges1993** [comment]
this encryption that I call ROSA evolution is a kind of post-quantum encryption.

**Comment by bghgary** [comment]
I don't know enough about encryption to comment, but I don't see any harm in adding a plugin.

**Comment by IuryBorges1993** [comment]
Vou fazer um em c++, na próxima semana.

**Comment by IuryBorges1993** [comment]
I'll do one in c ++, next week

**Comment by IuryBorges1993** [comment]
does anyone have a better approach?

And in what language could it be done?

What about file formats, how to protect them too?

**Comment by kefniark** [comment]
I dont really see how this problem is related to BabylonNative, it's really a javascript problem and usually part of the bundler step.

For a long time the two main solution were [Google closure](https://developers.google.com/closure) and [uglify](https://github.com/mishoo/UglifyJS#readme)
Nowadays there is a bit more choice, and [Terser](https://github.com/terser/terser) kinda became the new standard for JS minification because simple with good support (default for webpack, rollup, ...)

But if minification is not enough and obfuscation is really needed, there are some tools for that too, like https://obfuscator.io/
The obfuscation part usually come with some drawback:
* output size get bigger
* performance cost
so it's not always a good idea to obfuscate everything like vendors and things like that, but only focus on specific sensible part

**Comment by bghgary** [comment]
Closing for now. Consider adding an external plugin if this functionality is desired.
