### ISSUE TITLE
Extremely large large models cause BabylonReactNative demo app to crash.

### ISSUE THREAD

**Issue by RonnieAshlock** [BabylonJS/BabylonNative#349]
Very large and complicated meshes will not load in the BabylonReactNative demo app. 

Steps to repro: 

Try to load:

https://raw.githubusercontent.com/RonnieAshlock/TestAssets/master/GLB/CherryPicker.glb 

in a BabylonReactNative demo app.

**Comment by CedricGuillemet** [comment]
I could not repro the crash. Can you please push your branch with the changes to load the .glb so I can test it?

**Comment by RonnieAshlock** [comment]
Hi, Cedric. Ryan helped me push up my branch. Here is the URL:

https://github.com/RonnieAshlock/BabylonReactNative/tree/ModelTests

You should be able to just launch BabylonReactNative and repro the issue as I've set up SampleScene.ts to load the GLB that causes the app to crash. 

Thanks for taking a look at this.

**Comment by CedricGuillemet** [comment]
Hi Ronnie, I've tested your branch on iOS(device+sim) and it worked fine. I got the mesh displayed properly in AR mode as well.

**Comment by CedricGuillemet** [comment]
Ronnie is right! It's running out of memory.
The react http download tries to allocate 250Mb
![image](https://user-images.githubusercontent.com/1312968/89440984-be650800-d74c-11ea-9f99-341d56fe381a.png)
  
And the allocation profile
![image](https://user-images.githubusercontent.com/1312968/89441033-d177d800-d74c-11ea-9abb-e9f97fccc0a2.png)

I think you can repro the issue just by trying to dowload the file without BabylonNative.
I don't know why it makes a so big allocation for a 80Mb glb.

**Comment by bghgary** [comment]
@ryantrem @Alex-MSFT Can one of you take a look? We think this is React Native specific.

**Comment by ryantrem** [comment]
React Native's `XMLHttpRequest` takes the byte buffer, converts it to a base64 string, passes that string (by copy) to JavaScript, and finally it is converted in JavaScript back to a byte buffer. This results in too much memory pressure and leads to the crash. This has been addressed by allowing Babylon.js to use Babylon Native's `XMLHttpRequest` implementation instead of React Native's. See these PRs for details:
- https://github.com/BabylonJS/Babylon.js/pull/9148
- https://github.com/BabylonJS/BabylonNative/pull/442
- https://github.com/BabylonJS/BabylonReactNative/pull/94
