### ISSUE TITLE
Babylon.js seems work well in Hololens 2 platform while aframe.js and three.js does not, right? how can I use one of them to build a Cross-platform （Hololens/Oculus/IPad/Pixel）html （audio,model,video,text together）？

### ISSUE THREAD

**Issue by AIRS-EXR** [BabylonJS/BabylonNative#412]

**Comment by syntheticmagus** [comment]
Hi @AIRS-EXR,

These sound like awesome questions, but I think they might be better suited for discussion in the [Babylon.js Forum](https://forum.babylonjs.com/), especially since these seem like questions about Babylon.js more broadly rather than Babylon Native specifically. The forum discussion will pull in more Babylon.js expertise, too, whereas the issues on this repository are specifically about Babylon Native. Please add a new thread about this to the "Questions" category on the forum; hope to see you there!
