### ISSUE TITLE
Black screen on Android Emulator when loading a GLB with textures

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#443]
On Android Emulator on my machine, loading any GLB with textures ends up with a black screen. Create a box or loading a GLB box without textures work just fine. Also, if I enter AR, then the models also show up fine. This does not repro on device. Others have reported that this doesn't repro for them, so I'm not sure how many are seeing this. I tried all different settings (different API version, different OpenGL ES, etc.) to try to change the behavior, but it seems consistent on my machine.

Example GLBs that causes a black screen:
- https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxTextured/glTF/BoxTextured.gltf
- https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf

**Comment by ryantrem** [comment]
I'm not sure if the root cause is the same, but I see similar behavior on my Android device, it's just really inconsistent. If I run the Babylon React Native Playground app, and tap the "toggle engine screen" button to toggle the engine on/off 5-10 times, eventually I just get a black screen. If I toggle again, it typically renders the next time, but continuing to toggle will again lead to a black screen eventually.

**Comment by ryantrem** [comment]
This doesn't repro on device for me any more, so it must have had a different root cause that was resolved by the various fixes we've made around threading and/or memory management.

**Comment by CedricGuillemet** [comment]
I could not repro either.

**Comment by bghgary** [comment]
Seems like it no longer repros.
