### ISSUE TITLE
iOS Debug Build Model Flickering

### ISSUE THREAD

**Issue by rwedoff** [BabylonJS/BabylonNative#534]
When viewing a model in AR on iOS during a Debug build, the model and plane visualizations are flickering while moving the device around a bit. This does not repro in a Release Build for iOS.

![Dec-08-2020 13-41-21](https://user-images.githubusercontent.com/6679636/101544777-20cc5000-395b-11eb-9cd4-c1ad9c256d51.gif)

**Comment by Alex-MSFT** [comment]
My guess would be that this is because the metal renderer in BGFX does not wait for completion on "flip".  We could probably add a BGFX config setting for this or some way to toggle it on/off when in XR mode.

https://github.com/syntheticmagus/bgfx/blob/11681ba6a974878c304a404cd51e866b8f5deba5/src/renderer_mtl.mm#L3428
