### ISSUE TITLE
BabylonNative + ARKit

### ISSUE THREAD

**Issue by davidebaltieri31** [BabylonJS/BabylonNative#574]
Running the playground app with ar enabled on iOS doesn't work in debug, but runs fine in release.

In debug I get this error:
-[MTLDebugRenderCommandEncoder validateFramebufferWithRenderPipelineState:]:1228: failed assertion `For depth attachment, the render pipeline's pixelFormat (MTLPixelFormatInvalid) does not match the framebuffer's pixelFormat (MTLPixelFormatDepth32Float_Stencil8).

I'm on Big Sur, Xcode 12.3, cloned the repo from scratch, followed instructions to build on Mac+iOS and modified experience.js enabling ar.

**Comment by ryantrem** [comment]
Will you try disabling Metal API validation as described here: https://github.com/BabylonJS/BabylonReactNative/blob/master/Modules/@babylonjs/react-native/README.md#ios-configuration

Currently we must disable this due to the way our threading works (this is slowly being addressed), so it’s possible a new assertion snuck in that we weren’t aware of.

**Comment by davidebaltieri31** [comment]
Tried what you suggested and yes, after disabling Metal API validation it works in debug too.

**Comment by ryantrem** [comment]
@bghgary this is another issue that may be resolved by your frame buffer changes (since you are moving rendering onto the main thread).

**Comment by bghgary** [comment]
We believe this is fixed. @davidebaltieri31 Let use know if you continue to see the issue.
