### ISSUE TITLE
Rendering is wonky when transitioning to XR on Android

### ISSUE THREAD

**Issue by ryantrem** [BabylonJS/BabylonNative#649]
When transitioning to XR, the non-XR scene has some wonky rendering for a second or so. It looks to me like it is doing an `eglSwapBuffers` without having drawn anything new (so just switching back and forth between two already drawn frames). The consecutive frames need to be different to see this, so in Babylon Native Playground you can repro this by rotating the model with a pan gesture while it is transitioning to XR. Maybe this is caused by the render loop (driven by the consumer) to continue to run, but Babylon.js is not drawing anything (or even clearing the scene), so it just swaps back and forth between the two previously rendered frames, but I'm not really sure, just taking a guess.
![ARCore-render-transition-bug](https://user-images.githubusercontent.com/5084643/112670078-b104a700-8e1d-11eb-88ab-2e440fdc72a9.gif)

**Comment by syntheticmagus** [comment]
A few different things going on here, including some open discussions about when certain events should take place (such as for #661). In brief, `createDefaultXrExperienceAsync` in some cases returns surprisingly early, such as on Android when it returns before the XR view is actually displayed. This results in a few frames when the app believes it is rendering to an XR window, but the XR window is not yet visible and the original backbuffer is still displayed. This creates a scenario where the Graphics object is repeatedly calling `bgfx::frame` without having ever sent any work to the backbuffer; and because AR scenarios disable auto-clearing by default (which is a scene-wide setting), bgfx ends up repeatedly calling `eglSwapBuffers` without ever having sent instructions to do anything to the backbuffer, including clearing it. This creates the appearance of a cycling set of frames until the XR view is finally displayed, hiding the behavior.

It's likely that both Babylon.js and Babylon Native should make changes to prevent this behavior.

1. Babylon.js might want to consider a per-camera `autoClear` setting which would allow the XR view to not auto-clear while the main view continues to do so.
2. Babylon Native should consider not returning from XR session creation until the asynchronous portions of XR creation, including display initialization, have actually completed.

Neither of the preceding considerations are, strictly speaking, bugs, but they're likely behaviors we want to change anyway. However, in the unlikely event that those changes prove undesirable for other reasons, and for those who don't want to wait for such changes, simply doing the desired clearing manually during XR should result in the desired behavior.

```
const autoClearBackBufferDuringXr = function (scene, xr) {
    let observer = scene.onBeforeRenderObservable.add(() => {
        scene.getEngine().unBindFramebuffer();
        scene.getEngine().clear(scene.clearColor, true);
    });
    xr.baseExperience.sessionManager.onXRSessionEnded.add(() => {
        scene.onBeforeRenderObservable.remove(observer);
    });
};
```
