### ISSUE TITLE
Change repo projects to consume NPM packages

### ISSUE THREAD

**Issue by Drigax** [BabylonJS/BabylonNative#694]
Currently the development workflow requires developers to manually update the babylon.max.js whenever we need to update the engine. Some automation that updates the repo babylon.max.js whenever a new preview package is published would:

1) Remove the need of contributors to update this dependency manually
2) Make sure we're testing BabylonNative against the latest published Babylon.js release
3) Match behavior of consumers of this project that use the NPM package as well. (i.e: BabylonReactNative)

**Comment by Drigax** [comment]
Following up on discussion with @bghgary @chrisfromwork @rgerd 

It seems our plan of action is:
- [ ] Modify BabylonNative projects (Playground, ValidationTests) to consume babylon.js npm package
- [ ] Add cmake build step to install node dependencies
- [ ] Add watcher to regenerate babylon.js bundle on local change of package contents.

**Comment by ryantrem** [comment]
Adding a CMake build step to install node dependencies seems weird to me, because installing node dependencies is something you need to do less frequently than running CMake. To me it seems like something that belongs outside of CMake, either as a higher level script, or as a manual step (as it is today).

**Comment by bghgary** [comment]
We can bring this back if necessary.
