### ISSUE TITLE
Minimum Build Size

### ISSUE THREAD

**Issue by Schr3da** [BabylonJS/BabylonNative#713]
Hi,

Im currently looking into Babylon Native and would like to use it for and upcoming project. 
As I used it in past already for web stuff - I would this time look into the native part :D

Do you know what would be the minimum possible app size on iOS/Android for an empty project?

kind regards,
Schr3da

**Comment by bghgary** [comment]
The binary for iOS/Android is around 5MB right now where much of it is the shader compiler dependencies: gslang and SPIRV-Cross.

For Android, there are things we can do to reduce this size for Android if we remove the dependency on SPIRV-Cross. Since we are targeting Android OpenGL and eventually Vulkan, SPIRV-Cross shouldn't be necessary. Also, if you don't already have a JavaScript VM/engine, you have to add another 20MB to include one.

The JavaScript files themselves depend on what features the app needs for Babylon.js and can range from hundreds of kilobytes to tens of megabytes.

That said, we haven't done any work on minimizing the footprint yet, so there maybe things we can do to reduce the app size.

All of this is prior to zipping the package.

**Comment by bghgary** [comment]
If you have more questions on this, please use the [forum](https://forum.babylonjs.com/). Thanks!
