### ISSUE TITLE
Support GLSL functions that take a sampler2D as a parameter

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#732]
**Describe the bug**

[There's an assertion in GLslang that guards against trying to get an lvalue on an rvalue](https://github.com/KhronosGroup/glslang/blob/9f76fd13306334ae0d8a000ad62b5538cfb45641/SPIRV/SpvBuilder.cpp#L2913), and it occurs when we try to compile a shader containing a call to a function with a sampler2D parameter to SPIR-V:
https://github.com/BabylonJS/BabylonNative/blob/432f0db8e0b0ddd98fb9c7744572f87c9c16528b/Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp#L34

<img width="892" alt="function-spirv-callstack" src="https://user-images.githubusercontent.com/4724014/117337038-bd831300-ae51-11eb-897c-7806a864f9ee.PNG">

Looks like it happens when trying to traverse a function node.

**To Reproduce**
Here's a playground:
https://playground.babylonjs.com/#4VUT5V#1

I'm able to consistently reproduce the issue when I use a function that contains a sampler2D parameter, like this one:

```glsl
void testSampler(sampler2D inputTexture, vec2 textureCoord, out vec4 color)
{
    vec4 textureRead = texture(inputTexture, tan(textureCoord));
    color = texture(inputTexture, abs(fract(4.0 * (fract(textureRead.xy) * fract(textureRead.xz) * ticks))));
}
```

Manually inlining the function works, and other function calls work.

I'm not sure if this is a problem on our side setting up the Glslang graph or a problem in Glslang itself, so that might be the first step here.

**Other**
 - Platform: Win32

**Comment by syntheticmagus** [comment]
Just from a glance, this may be a lot trickier to get right than it seems on the surface. I haven't debugged it to know for sure, but `sampler2D` is tricky because it actually has to be split into two variables, a sampler and a texture. It actually has its own dedicated traverser to do this. Thus, if you're passing around samplers as parameters, to mimic that behavior in the modified shader we're probably going to have to manipulate the signature of the sampler-taking function itself because that function is now going to need to take an additional parameter. Is passing samplers as parameters a common or expected practice? If not, then given the complexity I anticipate to be associated with this, I recommend removing the bug flag and recategorizing this as a feature request because, if I'm right about what's causing this, it's less about fixing something that's broken than it is about supporting a usage pattern that we simply don't support yet.

**Comment by Popov72** [comment]
We have fixed this problem in WebGPU with an automatic inliner: you just have to tag the function with `#define inline` and process the shader code with the inliner:

https://github.com/BabylonJS/Babylon.js/blob/master/src/Engines/WebGPU/webgpuShaderProcessors.ts#L375-L378

We already have tagged all the shader functions with `#define inline` in the Babylon.js repo that took a sampler as a parameter. So on your side you should only have to use:
```typescript
let sci = new ShaderCodeInliner(code);
sci.debug = dbgShowDebugInliningProcess;
sci.processCode();
```

**Comment by Popov72** [comment]
And the sampler/texture split is handled in the shader processing code in this function:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Engines/WebGPU/webgpuShaderProcessors.ts#L144-L283

Basically, when we process a `uniform samplerXXX myOrigTexture` uniform, we output two `layout(...) uniform` variables, one for the sampler and one for the texture, something like:
```glsl
layout(set = ..., binding = ...) uniform ${componentType}${samplerType} ${name}Sampler;
layout(set = ..., binding = ...) uniform ${textureType} ${name}Texture
```
where ${name} is the name of the sampler in the original source code (`myOrigTexture` here).
And finally we generate:
```glsl
#define ${name} ${componentType}${samplerFunction}(${name}Texture, ${name}Sampler)
```
That way, the original name will be replaced in the final shader by the right construct, something like `samplerXXX(myOrigTextureTexture, myOrigTextureSampler)`: this is what needs to be passed to the `texture` lookup functions.

**Comment by bghgary** [comment]
We just follow what WebGPU does here, so I don't think there are any actions.
