### ISSUE TITLE
Conditional traversal crashes for ShaderCompilerD3D

### ISSUE THREAD

**Issue by rgerd** [BabylonJS/BabylonNative#734]
**Describe the bug**
I have a conditional in a vertex shader:
```hlsl
vec3 Result_Q177 = _Use_Global_Left_Index_ ? Global_Left_Index_Tip_Position.xyz : _Blob_Position_;
```
All variables involved are uniforms. Shader compilation crashes here:
https://github.com/BabylonJS/BabylonNative/blob/7fc7e3d41753e1efd408dd0ac9adb7272524d722/Plugins/NativeEngine/Source/ShaderCompilerD3D.cpp#L101

**To Reproduce**
The following shader reproduces the crash:
https://playground.babylonjs.com/#QPA82A#11

Seems like the crash only happens when you use a vec3 on one side and a vec4 on the other. I assume the crash is more general than that (for example it feels more likely to be because I'm accessing the .xyz on one of the clauses of the conditional), but this is a reliable repro.

**Screenshots**
Here's a call stack:
<img width="541" alt="conditional-traversal-stack" src="https://user-images.githubusercontent.com/4724014/117344034-ce378700-ae59-11eb-879e-662870b91116.PNG">

**Other**
 - Platform: Win32

**Comment by syntheticmagus** [comment]
I believe the bug is actually coming from a case in the traverser before the one that happens, which leaves the AST in an invalid state.

https://github.com/BabylonJS/BabylonNative/blob/ada433c1d8053b5620e40b5665eb65efdbdaaff3/Plugins/NativeEngine/Source/ShaderCompilerTraversers.cpp#L68-L72

This code always replaces the condition if the parent of the symbol to be replaced is a selection node, but it's not guaranteed that the condition is the symbol that should be replaced. Specifically, in a case like the repro case

```
result = uniformBool ? uniformA : uniformB;
```

everything to the right of the assignment operator goes into a selection node, and all three uniforms -- the condition, the true block, and the false block -- must be paved over with their struct-indexed replacements. Right now, the replacement for `uniformA` actually ends up (successfully) deleting and (unsuccessfully) replacing the replacement for `uniformBool`, which causes a few different problems that leave the AST in the state the cases the later traverser to crash.

The fix seems to be just checking which symbol should be replaced and replacing that one. To copy the pattern used on the condition, though, we'll have to wait for the [setters to be added to glslang](https://github.com/KhronosGroup/glslang/pull/2653). (The alternative to this would be to recreate the selection node using its existing public constructor and replace it in its parent, which wouldn't require modifying glslang but would involve jumping through a bunch more weird hoops on our end.) Once that PR goes through, we should be able to close this out once we update the glslang submodule in #769 and check that in.

**Comment by bghgary** [comment]
This is fixed now.
