### ISSUE TITLE
BabylonNative should support keyboard input

### ISSUE THREAD

**Issue by chrisfromwork** [BabylonJS/BabylonNative#737]
**For questions, please use the [forum](https://forum.babylonjs.com)**.

**Is your feature request related to a problem? Please describe.**
Samples (UWP and Win32 Playground etc) don't route key presses to the engine/js logic

**Describe the solution you'd like**
Samples should support some form of keyboard input

**Describe alternatives you've considered**
If I understand correctly, there are no work arounds for this because keyboard events don't reach the js engine

**Additional context**
Keyboard input logic should go into NativeInput compared to being some sort of one off samples workaround so that we can consume it in babylonreactnative as well

**Comment by ryantrem** [comment]
If anyone gets to this, please don't spend time adding keyboard support to the Playground's "sample" code for dealing with input. Rather, we should add keyboard support to `NativeInput` and finish the PR to switch the Playground apps over to using `NativeInput` instead of sample code for handling input. https://github.com/BabylonJS/BabylonNative/pull/610

**Comment by bghgary** [comment]
Overall, this kind of work is tracked by #173 which has been so far mostly on the Babylon.js side of things.

**Comment by bghgary** [comment]
@tymlipari Can you check on this?

**Comment by thomlucc** [comment]
supercede by #1143
