### ISSUE TITLE
Default backbuffer clearing to wrong color

### ISSUE THREAD

**Issue by syntheticmagus** [BabylonJS/BabylonNative#85]
![image](https://user-images.githubusercontent.com/33846034/67994110-e2654d00-fc00-11e9-9464-3718811665c2.png)

The purple color visible in this screenshot is the default color we provide to BGFX, but Babylon.js should be overriding this color with the Playground's blue. This is indicative that the clear state may not be being set properly for the default view.

**Comment by syntheticmagus** [comment]
![image](https://user-images.githubusercontent.com/33846034/67994679-aaabd480-fc03-11e9-8c5a-08df773bd2a9.png)
This is the color the backbuffer used to clear to.

**Comment by CedricGuillemet** [comment]
There was a setviewclear in setviewport method that was using the default BabylonNative color:
https://github.com/BabylonJS/BabylonNative/pull/82/files#diff-dbfa6ca10fa035a631932160cd003264L1349
Because there is a setviewport (and a viewId == 1), the viewId 0 was set to clear view with the right color but because of no drawcall in view 0, it wasn't cleared. so, I added a touch here:
https://github.com/BabylonJS/BabylonNative/pull/82/files#diff-21d665b1d21081b0ae44c5cce05bdf0dR72

**Comment by CedricGuillemet** [comment]
Will do the fix in this PR https://github.com/BabylonJS/BabylonNative/pull/86 as @bghgary suggested

**Comment by CedricGuillemet** [comment]
PR is merged. Should be fixed now. Closing.
